repositories:
- name: gitea-charts
  url: https://dl.gitea.com/charts/
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: metallb
  namespace: metallb
  chart: metallb/metallb
  values:
    - configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.5-192.168.1.10

- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  values:
    - controller:
        service:
          type: LoadBalancer

- name: gitea
  namespace: gitea
  chart: gitea-charts/gitea
  values:
    - service:
        type: LoadBalancer
        ports:
        - name: http
          port: 80
          targetPort: 3000
        ssh:
          annotations:
            metallb.universe.tf/allow-shared-ip: gitea
    - memcached:
        enabled: false
    - redis-cluster:
        enabled: false
    - redis:
        enabled: true
    - postgresql:
        enabled: true
    - postgresql-ha:
        enabled: false
    - persistence:
        enabled: true
    - ingress:
        enabled: true
        hosts:
        - host: git.homelab.local
          paths:
            - path: /
              pathType: Prefix
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          # kubernetes.io/ingress.class: "nginx"
          # cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # tls:
        # - secretName: gitea-tls
        #   hosts:
        #     - git.homelab.local
    - actions:
        enabled: true
        provisioning:
          enabled: true
    - gitea:
        config:
          database:
            DB_TYPE: postgres
          indexer:
            ISSUE_INDEXER_TYPE: bleve
            REPO_INDEXER_ENABLED: true
