#!/bin/bash
# combustion: network
set -euo pipefail

# Should be generated with `make setup`
source ./credentials.conf

# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1

# Set root password
echo "root:${ROOT_PASSWORD_HASH}" | chpasswd -e

# Allow rootless users to bind any port (0–65535)
echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/99-unprivileged-ports.conf

# Apply immediately
/sbin/sysctl -p /etc/sysctl.d/99-unprivileged-ports.conf

# Create user and add to wheel
groupadd -r wheel
mount /home
useradd  -G wheel -m -s /bin/bash "${USERNAME}" -p "${PASSWORD_HASH}"
mkdir -pm700 /home/core/.ssh/
umount /home

# Install dependencies and check for success
zypper --non-interactive install make git gnupg2

# Enable and start the SSH service
systemctl enable sshd.service

# Reboot after changes
systemctl reboot
